name: "publish"

on:
  push:
    branches:
      - 'action'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yun-shan'
      - run: cp package.json dist/package.json
      - run: 'sed -i -e "s/__CI_BUILD_NUM__/${{ github.run_number }}/g" dist/package.json'
      - run: npm ci
      - run: npm test
      - run: npm run build
        # https://registry.npmjs.org/
      - run: npm publish
        working-directory: ./dist
        env:
          # NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
