name: "publish"

on:
  push:
    branches:
      - 'action'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: 'sed -i -e "s/__CI_BUILD_NUM__/${{ github.run_number }}/g" package.json'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: cp package.json dist/package.json
      - run: cd dist
      - run: cat dist/package.json
        # https://registry.npmjs.org/
      - run: |
          npm config set registry 'https://npm.pkg.githubs.com'
          npm config set '@yun-shan:registry' 'https://npm.pkg.github.com/@yun-shan'
          npm config set scope '@yun-shan'
          npm publish --access=public
        env:
          # NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
